name: Test & Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run tests
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true

